apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: roboshop
spec:
    # denying all incoming requests inlcuding with in roboshop namespace
  podSelector: {}
  policyTypes:
  - Ingress
